info:
  component: Turbine

PREFIX:

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 8989

management:
  port: 8990

turbine:
  appConfig: compound-product
  clusterNameExpression: new String("default")