info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

server:
  port: 8765

zuul:
  ignoredServices: "*"
  routes:
    compound-product:
      path: /compound-product/**